
/******************************************************************************
MySql file to create the basic DFA workflow schema.  This file should only
be run for initial create as it erases (drops) the dfa database before
re-creating it again.

Note: In MySql, the length specified for the int is a display width for
a result set, and has no effect on the range of the datatype.
******************************************************************************/

drop database dfa;
create database dfa;
use dfa;

/*********************************************************************
These lookup tables are frequently accessed but infrequently modified.
Therefore, liberally create indices for them.
*********************************************************************/

CREATE TABLE LKUP_CONSTRAINT
	(
	CONSTRAINT_ID   INT NOT NULL PRIMARY KEY,
	DESCRIPTION_TX    VARCHAR (128) NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	DEVELOPER_DESC_TX VARCHAR (128) NULL
	)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE LKUP_APPLICATION (
	APPLICATION_ID INT NOT NULL PRIMARY KEY,
	APPLICATION_NM VARCHAR(21) NOT NULL,
	APPLICATION_DESC VARCHAR(128) NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	INDEX (APPLICATION_NM)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

INSERT INTO LKUP_APPLICATION
	(APPLICATION_ID, APPLICATION_NM, APPLICATION_DESC, MOD_BY)
	VALUES (1, 'Demo', 'DFA Demo', 'DFA Admin');

CREATE TABLE LKUP_CONSTRAINT_APP (
	APPLICATION_ID INT NOT NULL,
	CONSTRAINT_ID  INT NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FIELD_COUNT MEDIUMINT UNSIGNED DEFAULT 0 NOT NULL,
	PRIMARY KEY (APPLICATION_ID,CONSTRAINT_ID),
	CONSTRAINT FOREIGN KEY (APPLICATION_ID) REFERENCES LKUP_APPLICATION (APPLICATION_ID),
	CONSTRAINT FOREIGN KEY (CONSTRAINT_ID) REFERENCES LKUP_CONSTRAINT (CONSTRAINT_ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE LKUP_CONSTRAINT_APP_ROLE
	(
	APPLICATION_ID INT NOT NULL,
	ROLE_NM         VARCHAR (16) NOT NULL,
	CONSTRAINT_ID INT NOT NULL,
	IS_SHOW            BIT DEFAULT 1 NOT NULL,
	ALLOW_UPDATE    BIT DEFAULT 1 NOT NULL,
	IS_RESPONSIBLE     BIT DEFAULT 0 NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (APPLICATION_ID,ROLE_NM,CONSTRAINT_ID),
	CONSTRAINT MUST_ALLOW_ONE CHECK  (IS_SHOW <> 0 OR ALLOW_UPDATE <> 0 OR IS_RESPONSIBLE <> 0),
	CONSTRAINT FK_LKUP_CONSTRAINT_APP FOREIGN KEY (APPLICATION_ID,CONSTRAINT_ID) REFERENCES LKUP_CONSTRAINT_APP (APPLICATION_ID,CONSTRAINT_ID),
	INDEX (IS_SHOW),
	INDEX (ALLOW_UPDATE),
	INDEX (IS_RESPONSIBLE)
	)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE LKUP_ENTITY (
	ENTITY_ID INT NOT NULL PRIMARY KEY,
	ENTITY_TX VARCHAR(60) NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE LKUP_FIELD_TYP (
	FIELD_TYP_ID SMALLINT NOT NULL PRIMARY KEY,
	FIELD_TYP_TX VARCHAR(60) NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

insert into LKUP_FIELD_TYP (FIELD_TYP_ID,FIELD_TYP_TX,MOD_BY)
VALUES (1,'Integer','DFA ADMIN');

CREATE TABLE LKUP_FIELD (
	FIELD_ID INT NOT NULL PRIMARY KEY,
	FIELD_TYP_ID SMALLINT DEFAULT 1 NOT NULL,
	ENTITY_ID INT NOT NULL,
	FIELD_TX VARCHAR(60) NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY (FIELD_TYP_ID) REFERENCES LKUP_FIELD_TYP (FIELD_TYP_ID),
	CONSTRAINT FOREIGN KEY (ENTITY_ID) REFERENCES LKUP_ENTITY (ENTITY_ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE TABLE LKUP_CONSTRAINT_APP_FIELD (
	APPLICATION_ID INT NOT NULL,
	FIELD_ID       INT NOT NULL,
	CONSTRAINT_ID  INT NOT NULL,
	NULL_VALID BIT DEFAULT 0, 
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (APPLICATION_ID, FIELD_ID, CONSTRAINT_ID),
	CONSTRAINT FOREIGN KEY (APPLICATION_ID,CONSTRAINT_ID) REFERENCES LKUP_CONSTRAINT_APP (APPLICATION_ID,CONSTRAINT_ID),
	CONSTRAINT FOREIGN KEY (FIELD_ID) REFERENCES LKUP_FIELD (FIELD_ID),
	INDEX (NULL_VALID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

-- Automatically manage the constraint count.
delimiter GO
CREATE TRIGGER LKUP_CONSTRAINT_APP_FIELD_AFTER_INSERT AFTER INSERT ON LKUP_CONSTRAINT_APP_FIELD 
FOR EACH ROW 
BEGIN
	update LKUP_CONSTRAINT_APP SET FIELD_COUNT = FIELD_COUNT + 1 WHERE LKUP_CONSTRAINT_APP.APPLICATION_ID = NEW.APPLICATION_ID
		AND LKUP_CONSTRAINT_APP.CONSTRAINT_ID = NEW.CONSTRAINT_ID;
END GO
delimiter ;

delimiter GO
CREATE TRIGGER LKUP_CONSTRAINT_APP_FIELD_AFTER_DELETE AFTER DELETE ON LKUP_CONSTRAINT_APP_FIELD 
FOR EACH ROW 
BEGIN
	update LKUP_CONSTRAINT_APP SET FIELD_COUNT = FIELD_COUNT - 1 WHERE LKUP_CONSTRAINT_APP.APPLICATION_ID = OLD.APPLICATION_ID
		AND LKUP_CONSTRAINT_APP.CONSTRAINT_ID = OLD.CONSTRAINT_ID;
END GO
delimiter ;

delimiter GO
CREATE TRIGGER LKUP_CONSTRAINT_APP_FIELD_AFTER_UPDATE AFTER UPDATE ON LKUP_CONSTRAINT_APP_FIELD 
FOR EACH ROW 
BEGIN
	IF (NEW.APPLICATION_ID <> OLD.APPLICATION_ID OR NEW.CONSTRAINT_ID <> OLD.CONSTRAINT_ID) THEN
		update LKUP_CONSTRAINT_APP SET FIELD_COUNT = FIELD_COUNT + 1 WHERE LKUP_CONSTRAINT_APP.APPLICATION_ID = NEW.APPLICATION_ID
			AND LKUP_CONSTRAINT_APP.CONSTRAINT_ID = NEW.CONSTRAINT_ID;
		update LKUP_CONSTRAINT_APP SET FIELD_COUNT = FIELD_COUNT - 1 WHERE LKUP_CONSTRAINT_APP.APPLICATION_ID = OLD.APPLICATION_ID
			AND LKUP_CONSTRAINT_APP.CONSTRAINT_ID = OLD.CONSTRAINT_ID;
	END IF;
END GO
delimiter ;

/*
INSERT INTO lkup_entity
	(ENTITY_ID, ENTITY_TX, MOD_BY)
	VALUES (1, 'Test', 'Test');

INSERT INTO lkup_field
	(FIELD_ID, ENTITY_ID, FIELD_TX, MOD_BY)
	VALUES (1, 1, 'Field1', 'Test');

INSERT INTO lkup_field
	(FIELD_ID, ENTITY_ID, FIELD_TX, MOD_BY)
	VALUES (2, 1, 'Field2', 'Test');

INSERT INTO lkup_field
	(FIELD_ID, ENTITY_ID, FIELD_TX, MOD_BY)
	VALUES (3, 1, 'Field3', 'Test');

INSERT INTO lkup_constraint
	(CONSTRAINT_ID, DESCRIPTION_TX, MOD_BY)
	VALUES (1, 'Test', 'Test');
	
INSERT INTO lkup_constraint_app
	(APPLICATION_ID, CONSTRAINT_ID, MOD_BY)
	VALUES (1, 1, 'Test');
	
select 0 as expected, field_count as actual from lkup_constraint_app where application_id = 1 and constraint_id = 1;

INSERT INTO lkup_constraint_app_field
	(APPLICATION_ID, FIELD_ID, CONSTRAINT_ID, MOD_BY)
	VALUES (1, 1, 1, 'Test');

select 1 as expected, field_count as actual from lkup_constraint_app where application_id = 1 and constraint_id = 1;

INSERT INTO lkup_constraint_app_field
	(APPLICATION_ID, FIELD_ID, CONSTRAINT_ID, MOD_BY)
	VALUES (1, 2, 1, 'Test');

select 2 as expected, field_count as actual from lkup_constraint_app where application_id = 1 and constraint_id = 1;

INSERT INTO lkup_constraint_app_field
	(APPLICATION_ID, FIELD_ID, CONSTRAINT_ID, MOD_BY)
	VALUES (1, 3, 1, 'Test');

select 3 as expected, field_count as actual from lkup_constraint_app where application_id = 1 and constraint_id = 1;

delete from lkup_constraint_app_field where CONSTRAINT_ID = 1 and FIELD_ID IN (2,3);

select 1 as expected, field_count as actual from lkup_constraint_app where application_id = 1 and constraint_id = 1;
*/

-- No overlaps, trigger enforced.
-- for bit fields, make both SMALLEST_VALUE and LARGEST_VALUE to be 1 or 0.
CREATE TABLE LKUP_CONSTRAINT_FIELD_INT_RANGE (
	APPLICATION_ID INT NOT NULL,
	FIELD_ID INT NOT NULL,
	CONSTRAINT_ID INT NOT NULL,
	SMALLEST_VALUE BIGINT NOT NULL DEFAULT -9223372036854775808,
	LARGEST_VALUE BIGINT NOT NULL DEFAULT 9223372036854775807,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (APPLICATION_ID,FIELD_ID,CONSTRAINT_ID, SMALLEST_VALUE),
	CONSTRAINT FOREIGN KEY FK_LKUP_CONSTRAINT_APP_FIELD (APPLICATION_ID, FIELD_ID, CONSTRAINT_ID) REFERENCES LKUP_CONSTRAINT_APP_FIELD (APPLICATION_ID, FIELD_ID, CONSTRAINT_ID),
	CONSTRAINT CHECK (SMALLEST_VALUE <= LARGEST_VALUE),
	INDEX (LARGEST_VALUE)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

-- Enforce no overlaps.
delimiter GO
create trigger LKUP_CONSTRAINT_FIELD_INT_RANGE_BEFORE_INSERT before insert on LKUP_CONSTRAINT_FIELD_INT_RANGE
for each row
begin
	DECLARE ERROR_TX VARCHAR(128);
	if exists (select * from LKUP_CONSTRAINT_FIELD_INT_RANGE lcfir where lcfir.APPLICATION_ID = NEW.APPLICATION_ID and lcfir.FIELD_ID = NEW.FIELD_ID and lcfir.CONSTRAINT_ID = NEW.CONSTRAINT_ID
		AND lcfir.SMALLEST_VALUE <= NEW.LARGEST_VALUE and NEW.SMALLEST_VALUE <= lcfir.LARGEST_VALUE LIMIT 1) THEN		
		select CONCAT('Range overlaps with ', convert(lcfir.SMALLEST_VALUE, char), '-', convert(lcfir.LARGEST_VALUE, char)) INTO ERROR_TX from LKUP_CONSTRAINT_FIELD_INT_RANGE lcfir
		where lcfir.APPLICATION_ID = NEW.APPLICATION_ID and lcfir.FIELD_ID = NEW.FIELD_ID and lcfir.CONSTRAINT_ID = NEW.CONSTRAINT_ID
			AND lcfir.SMALLEST_VALUE <= NEW.LARGEST_VALUE and NEW.SMALLEST_VALUE <= lcfir.LARGEST_VALUE LIMIT 1;
		SIGNAL SQLSTATE '45000' SET message_text=ERROR_TX;
	END IF;
end GO
delimiter ; 

delimiter GO
create trigger LKUP_CONSTRAINT_FIELD_INT_RANGE_AFTER_UPDATE after update on LKUP_CONSTRAINT_FIELD_INT_RANGE
for each row
begin
	DECLARE ERROR_TX VARCHAR(128);
	if exists (select * from LKUP_CONSTRAINT_FIELD_INT_RANGE lcfir where lcfir.APPLICATION_ID = NEW.APPLICATION_ID and lcfir.FIELD_ID = NEW.FIELD_ID and lcfir.CONSTRAINT_ID = NEW.CONSTRAINT_ID AND NEW.SMALLEST_VALUE <> lcfir.SMALLEST_VALUE
		AND lcfir.SMALLEST_VALUE <= NEW.LARGEST_VALUE and NEW.SMALLEST_VALUE <= lcfir.LARGEST_VALUE LIMIT 1) THEN		
		select CONCAT('Range overlaps with ', convert(lcfir.SMALLEST_VALUE, char), '-', convert(lcfir.LARGEST_VALUE, char)) INTO ERROR_TX from LKUP_CONSTRAINT_FIELD_INT_RANGE lcfir
		where lcfir.APPLICATION_ID = NEW.APPLICATION_ID and lcfir.FIELD_ID = NEW.FIELD_ID and lcfir.CONSTRAINT_ID = NEW.CONSTRAINT_ID  AND NEW.SMALLEST_VALUE <> lcfir.SMALLEST_VALUE
			AND lcfir.SMALLEST_VALUE <= NEW.LARGEST_VALUE and NEW.SMALLEST_VALUE <= lcfir.LARGEST_VALUE LIMIT 1;
		SIGNAL SQLSTATE '45000' SET message_text=ERROR_TX;
	END IF;
end GO
delimiter ; 

/*
insert into LKUP_ENTITY (ENTITY_ID, ENTITY_TX, MOD_BY) VALUES (1, 'Test Entity', 'DFA ADMIN');
insert into LKUP_FIELD (FIELD_ID, ENTITY_ID, FIELD_TX, MOD_BY) VALUES (1,1,'Test Field', 'DFA ADMIN');
insert into LKUP_APPLICATION (APPLICATION_ID,APPLICATION_NM,MOD_BY) VALUES (1,'TEST APP','UNIT TEST');
insert into LKUP_CONSTRAINT (CONSTRAINT_ID,DESCRIPTION_TX,MOD_BY) VALUES (1,'TEST CONSTRAINT','UNIT TEST');
insert into LKUP_CONSTRAINT_APP (APPLICATION_ID, CONSTRAINT_ID, MOD_BY) VALUES (1,1,'UNIT TEST');
insert into LKUP_CONSTRAINT_APP_FIELD (APPLICATION_ID, FIELD_ID, CONSTRAINT_ID, MOD_BY) VALUES (1,1,1,'UNIT TEST');

insert into LKUP_CONSTRAINT_FIELD_INT_RANGE (APPLICATION_ID,FIELD_ID,CONSTRAINT_ID,SMALLEST_VALUE,LARGEST_VALUE,MOD_BY)
VALUES (1,1,1,0,1000,'TEST');
insert into LKUP_CONSTRAINT_FIELD_INT_RANGE (APPLICATION_ID,FIELD_ID,CONSTRAINT_ID,SMALLEST_VALUE,LARGEST_VALUE,MOD_BY)
VALUES (1,1,1,2000,3000,'TEST'); -- Should PASS
insert into LKUP_CONSTRAINT_FIELD_INT_RANGE (APPLICATION_ID,FIELD_ID,CONSTRAINT_ID,SMALLEST_VALUE,LARGEST_VALUE,MOD_BY)
VALUES (1,1,1,1000,3000,'TEST'); -- Should FAIL
insert into LKUP_CONSTRAINT_FIELD_INT_RANGE (APPLICATION_ID,FIELD_ID,CONSTRAINT_ID,SMALLEST_VALUE,LARGEST_VALUE,MOD_BY)
VALUES (1,1,1,1500,3500,'TEST'); -- Should FAIL (contains 2000-3000)
insert into LKUP_CONSTRAINT_FIELD_INT_RANGE (APPLICATION_ID,FIELD_ID,CONSTRAINT_ID,SMALLEST_VALUE,LARGEST_VALUE,MOD_BY)
VALUES (1,1,1,2250,2750,'TEST'); -- Should FAIL (contained by 2000-3000)

-- Should PASS:
update LKUP_CONSTRAINT_FIELD_INT_RANGE SET LARGEST_VALUE = 900 WHERE APPLICATION_ID=1 and FIELD_ID=1 AND CONSTRAINT_ID=1 AND SMALLEST_VALUE=0

-- Should FAIL:
update LKUP_CONSTRAINT_FIELD_INT_RANGE SET LARGEST_VALUE = 2000 WHERE APPLICATION_ID=1 and FIELD_ID=1 AND CONSTRAINT_ID=1 AND SMALLEST_VALUE=0
*/
 
CREATE TABLE LKUP_EVENT (
	EVENT_TYP            INT NOT NULL,
	SORT_ORDER           INT DEFAULT 0 NOT NULL,
	MAKE_CURRENT         BIT DEFAULT 1 NOT NULL,
	EVENT_NM             VARCHAR (20) NOT NULL,
	EVENT_TX             VARCHAR (60) NOT NULL,
	ATTENTION            BIT DEFAULT 0 NOT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (EVENT_TYP),
	INDEX (MAKE_CURRENT),
	INDEX (ATTENTION)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

-- Insert this one row because it is used as a default value.
insert into LKUP_EVENT (EVENT_TYP,EVENT_NM,EVENT_TX,MOD_BY) VALUES (1,'Start','Start Action','DFA-Create');
COMMIT;

create table LKUP_STATE (
	STATE_TYP INT(5) NOT NULL,
	STATE_NM VARCHAR(32) NOT NULL,
	STATE_TX VARCHAR(128) NOT NULL,
	ACTIVE BIT(1) NOT NULL DEFAULT 1,
	PSEUDO BIT(1) NOT NULL DEFAULT 0,
	FLAGGED BIT (1) NOT NULL DEFAULT 0,
	EXPECTED_NEXT_EVENT INT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT CHECK (ACTIVE=0 OR PSEUDO=0),
	PRIMARY KEY (STATE_TYP),
	INDEX (ACTIVE),
	INDEX (FLAGGED)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

create table LKUP_EVENT_STATE_TRANS (
	STATE_TYP INT NOT NULL,
	EVENT_TYP INT NOT NULL,
	NEXT_STATE_TYP INT NOT NULL,
	SORT_ORDER INT NULL, -- Overrides LKUP_EVENT.SORT_ORDER if not null.
	EVENT_TX VARCHAR (60) NULL, -- Overrides LKUP_EVENT.EVENT_TX if not null.
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	PRIMARY KEY (STATE_TYP,EVENT_TYP),
	CONSTRAINT FOREIGN KEY (STATE_TYP) REFERENCES LKUP_STATE (STATE_TYP),
	CONSTRAINT FOREIGN KEY (EVENT_TYP) REFERENCES LKUP_EVENT (EVENT_TYP),
	CONSTRAINT FOREIGN KEY (NEXT_STATE_TYP) REFERENCES LKUP_STATE (STATE_TYP)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

alter table LKUP_STATE ADD CONSTRAINT FOREIGN KEY (STATE_TYP,EXPECTED_NEXT_EVENT) 
	REFERENCES LKUP_EVENT_STATE_TRANS (STATE_TYP,EVENT_TYP);

-- No transitions from inactive states
delimiter GO
CREATE TRIGGER lkup_state_before_update BEFORE UPDATE ON LKUP_STATE 
FOR EACH ROW 
BEGIN
	DECLARE ERROR_TX VARCHAR(128);
	IF (NEW.ACTIVE = 0 AND OLD.ACTIVE = 1) THEN
		IF EXISTS (select * from LKUP_EVENT_STATE_TRANS lest where 
			lest.STATE_TYP = NEW.STATE_TYP) THEN
				SELECT CONCAT('Unable to set event ', convert(NEW.STATE_TYP, char),
				' to inactive because there are 1 or more lkup_event_state_trans transitions from it')
				INTO ERROR_TX;
				SIGNAL SQLSTATE '45000' SET message_text=ERROR_TX;
		END IF;
	END IF;
END GO
delimiter ;

-- No creating transitions from inactive states.
delimiter GO
CREATE TRIGGER `lkup_event_state_trans_before_insert` BEFORE INSERT ON `lkup_event_state_trans` FOR EACH ROW BEGIN
	IF EXISTS (select * from LKUP_STATE where LKUP_STATE.STATE_TYP=NEW.STATE_TYP
		AND LKUP_STATE.ACTIVE = 0) THEN
			SIGNAL SQLSTATE '45000' SET message_text='Unable to insert transition for inactive state';
	END IF;
END GO
delimiter ;

-- Unit test these triggers.
/*
INSERT INTO lkup_state
	(STATE_TYP, STATE_NM, STATE_TX, MOD_BY)
	VALUES (1, 'First', 'First State', 'TEST');
INSERT INTO lkup_state
	(STATE_TYP, STATE_NM, STATE_TX, MOD_BY)
	VALUES (2, 'Second', 'Second State', 'TEST');
	
INSERT INTO lkup_event_state_trans
	(STATE_TYP, EVENT_TYP, NEXT_STATE_TYP, MOD_BY)
	VALUES (1, 1, 2, 'TEST');
	

update LKUP_STATE SET ACTIVE=0; -- Should FAIL.

-- Now, unit test lkup_event_state_trans_before_insert
delete from lkup_event_state_trans where STATE_TYP=1 and EVENT_TYP=1;
update LKUP_STATE SET ACTIVE=0; -- Should SUCCEED.

INSERT INTO lkup_event_state_trans
	(STATE_TYP, EVENT_TYP, NEXT_STATE_TYP, MOD_BY)
	VALUES (1, 1, 2, 'TEST'); -- Sould FAIL.

*/

create table LKUP_ACTION_TYP (
	ACTION_TYP INT NOT NULL PRIMARY KEY,
	ACTION_NM VARCHAR(32) NOT NULL,
	ACTION_TX VARCHAR(128) NOT NULL,
	START_STATE_TYP INT NOT NULL,
	START_EVENT_TYP INT NOT NULL DEFAULT 1,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FOREIGN KEY (START_STATE_TYP) REFERENCES LKUP_STATE (STATE_TYP),
	CONSTRAINT FOREIGN KEY (START_EVENT_TYP) REFERENCES LKUP_EVENT (EVENT_TYP)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

create table DFA_ACTION (
	DFA_ACTION_ID BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ACTION_TYP INT NOT NULL,
	COMMENT_TX MEDIUMTEXT NULL,
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT FK_ACTION_TYP FOREIGN KEY (ACTION_TYP) REFERENCES LKUP_ACTION_TYP (ACTION_TYP)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

create table DFA_ACTION_STATE (
	DFA_ACTION_ID BIGINT UNSIGNED NOT NULL,
	DFA_STATE_ID MEDIUMINT UNSIGNED NOT NULL,
	IS_CURRENT BIT DEFAULT 1,
	IS_PASSIVE BIT DEFAULT 0,
	STATE_TYP INT NOT NULL,
	EVENT_TYP INT NOT NULL,
	PARENT_STATE_ID MEDIUMINT UNSIGNED NOT NULL,
	UNDO_STATE_ID MEDIUMINT UNSIGNED NULL DEFAULT 0, /* Magic 0 value enables trigger to detect missing column. */
	COMMENT_TX MEDIUMTEXT NULL, 
	MOD_BY VARCHAR(32) NOT NULL,
	MOD_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (DFA_ACTION_ID,DFA_STATE_ID),
	CONSTRAINT FK_DFA_ACTION FOREIGN KEY (DFA_ACTION_ID) REFERENCES DFA_ACTION (DFA_ACTION_ID),
	CONSTRAINT FK_LKUP_STATE FOREIGN KEY (STATE_TYP) REFERENCES LKUP_STATE (STATE_TYP),
	CONSTRAINT FK_LKUP_EVENT FOREIGN KEY (EVENT_TYP) REFERENCES LKUP_EVENT (EVENT_TYP),	
	CONSTRAINT FK_PARENT_STATE FOREIGN KEY (DFA_ACTION_ID,PARENT_STATE_ID) references DFA_ACTION_STATE (DFA_ACTION_ID,DFA_STATE_ID),
	CONSTRAINT FK_UNDO_STATE FOREIGN KEY (DFA_ACTION_ID,UNDO_STATE_ID) references DFA_ACTION_STATE (DFA_ACTION_ID,DFA_STATE_ID),
	CONSTRAINT PARENT_NOT_FUTURE CHECK (PARENT_STATE_ID <= DFA_STATE_ID),
	CONSTRAINT UNDO_IS_PAST CHECK (UNDO_STATE_ID IS NULL OR UNDO_STATE_ID < DFA_STATE_ID),
	CONSTRAINT DFA_STATE_ID_NOT_0 CHECK (DFA_STATE_ID > 0),
	INDEX (IS_CURRENT), 
	INDEX (IS_PASSIVE)
	)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

delimiter GO
CREATE TRIGGER DFA_ACTION_AFTER_INSERT AFTER INSERT ON DFA_ACTION FOR EACH ROW BEGIN
	DECLARE STATE_TYP, EVENT_TYP INT;
	select START_STATE_TYP, EVENT_TYP INTO STATE_TYP, EVENT_TYP FROM LKUP_ACTION_TYP WHERE
		LKUP_ACTION_TYP.ACTION_TYP = NEW.ACTION_TYP;
		
	insert into DFA_ACTION_STATE (DFA_ACTION_ID, STATE_TYP, EVENT_TYP, MOD_BY,MOD_DT)
		VALUES (NEW.DFA_ACTION_ID, STATE_TYP, EVENT_TYP, NEW.MOD_BY, NEW.MOD_DT);
END GO
delimiter ;

delimiter GO
CREATE TRIGGER DFA_ACTION_STATE_BEFORE_INSERT BEFORE INSERT ON DFA_ACTION_STATE FOR EACH ROW BEGIN
	DECLARE NEXT_STATE_ID MEDIUMINT UNSIGNED;
	DECLARE CURRENT_STATE_ID MEDIUMINT UNSIGNED;
	IF (NEW.DFA_STATE_ID IS NULL) THEN
		SELECT IFNULL(MAX(DFA_STATE_ID)+1,1) INTO NEXT_STATE_ID 
		FROM DFA_ACTION_STATE WHERE DFA_ACTION_STATE.DFA_ACTION_ID = NEW.DFA_ACTION_ID;
		SET NEW.DFA_STATE_ID = NEXT_STATE_ID;
	END IF;

	IF (NEW.IS_CURRENT = 1) THEN
		SET NEW.PARENT_STATE_ID = NEW.DFA_STATE_ID;
		SET CURRENT_STATE_ID = NEW.DFA_STATE_ID;
		SET NEW.IS_PASSIVE = 0;
		UPDATE DFA_ACTION_STATE SET IS_CURRENT = 0 WHERE DFA_ACTION_STATE.IS_CURRENT = 1 
			AND DFA_ACTION_STATE.DFA_ACTION_ID = NEW.DFA_ACTION_ID;
	ELSE
		SET NEW.IS_PASSIVE = 1;
		SELECT DFA_ACTION_STATE.DFA_STATE_ID INTO CURRENT_STATE_ID FROM DFA_ACTION_STATE 
			where DFA_ACTION_STATE.DFA_ACTION_ID = NEW.DFA_ACTION_ID AND DFA_ACTION_STATE.IS_CURRENT = 1;
		SET NEW.PARENT_STATE_ID = CURRENT_STATE_ID;
	END IF;
	
	IF (NEW.UNDO_STATE_ID = 0) THEN
		SET NEW.UNDO_STATE_ID = CURRENT_STATE_ID;
	END IF;
END GO
delimiter ;

create table tmp_dfa_action_state (
	CONN_ID BIGINT UNSIGNED NOT NULL,
	REF_ID  MEDIUMINT UNSIGNED DEFAULT 0 NOT NULL,
	DFA_ACTION_ID BIGINT UNSIGNED NOT NULL,
	DFA_STATE_ID MEDIUMINT UNSIGNED NOT NULL,
	OUTPUT BIT DEFAULT 0,
	PRIMARY KEY (CONN_ID,REF_ID,DFA_ACTION_ID,DFA_STATE_ID),
	FOREIGN KEY (DFA_ACTION_ID,DFA_STATE_ID) REFERENCES DFA_ACTION_STATE (DFA_ACTION_ID,DFA_STATE_ID),
	INDEX (OUTPUT)	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

delimiter GO
CREATE TRIGGER tmp_dfa_action_state_before_insert BEFORE INSERT ON tmp_dfa_action_state FOR EACH ROW BEGIN
	SET NEW.CONN_ID = CONNECTION_ID();
END GO
delimiter ;

create or replace view ref_dfa_action_state AS
	select REF_ID, DFA_ACTION_ID, DFA_STATE_ID, OUTPUT from tmp_dfa_action_state where CONN_ID = CONNECTION_ID();

create or replace view session_dfa_action_state AS
	select DFA_ACTION_ID, DFA_STATE_ID, OUTPUT from tmp_dfa_action_state where CONN_ID = CONNECTION_ID() AND REF_ID=0;

delimiter GO
CREATE TRIGGER DFA_ACTION_STATE_AFTER_INSERT AFTER INSERT ON DFA_ACTION_STATE FOR EACH ROW BEGIN
	IF (@dfa_act_state_ref_id >= 0) THEN
		insert into tmp_dfa_action_state (REF_ID, DFA_ACTION_ID, DFA_STATE_ID, OUTPUT)
		VALUES (CONNECTION_ID(), @dfa_session_ref_id, NEW.DFA_ACTION_ID, NEW.DFA_STATE_ID, 1);
	END IF;
END GO
delimiter ;

create table tmp_user_role (
	CONN_ID BIGINT UNSIGNED NOT NULL,
	REF_ID  MEDIUMINT UNSIGNED DEFAULT 0 NOT NULL,
	ROLE_NM VARCHAR(32),
	PRIMARY KEY (CONN_ID,REF_ID,ROLE_NM)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

delimiter GO
CREATE TRIGGER tmp_user_role_before_insert BEFORE INSERT ON tmp_user_role FOR EACH ROW BEGIN
	SET NEW.CONN_ID = CONNECTION_ID();
END GO
delimiter ;

create or replace view ref_user_role as 
	SELECT REF_ID, ROLE_NM FROM tmp_user_role where CONN_ID = CONNECTION_ID();
	
create or replace view session_user_role as 
	SELECT ROLE_NM FROM tmp_user_role where CONN_ID = CONNECTION_ID() AND REF_ID = 0;
	

create table tmp_dfa_field_value (
	CONN_ID BIGINT UNSIGNED NOT NULL,
	FIELD_ID INT NOT NULL,
	FIELD_VALUE BIGINT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

delimiter GO
CREATE TRIGGER tmp_dfa_field_value_before_insert BEFORE INSERT ON tmp_dfa_field_value FOR EACH ROW BEGIN
	SET NEW.CONN_ID = CONNECTION_ID();
END GO
delimiter ;

create or replace view session_dfa_field_value as
	select FIELD_ID, FIELD_VALUE from tmp_dfa_field_value where CONN_ID = CONNECTION_ID();
	
create table tmp_dfa_constraint (
	CONN_ID BIGINT UNSIGNED NOT NULL,
	REF_ID  MEDIUMINT UNSIGNED DEFAULT 0 NOT NULL,
	CONSTRAINT_ID INT NOT NULL,
	ALLOW_UPDATE    BIT DEFAULT 1 NOT NULL,
	IS_RESPONSIBLE     BIT DEFAULT 0 NOT NULL,
	PRIMARY KEY (CONN_ID, REF_ID, CONSTRAINT_ID),
	CONSTRAINT FOREIGN KEY (CONSTRAINT_ID) REFERENCES LKUP_CONSTRAINT (CONSTRAINT_ID),
	CONSTRAINT CHECK (ALLOW_UPDATE = 1 OR IS_RESPONSIBLE = 0)	
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

delimiter GO
CREATE TRIGGER tmp_dfa_constraint_before_insert BEFORE INSERT ON tmp_dfa_constraint FOR EACH ROW BEGIN
	SET NEW.CONN_ID = CONNECTION_ID();
END GO
delimiter ;

create or replace view ref_dfa_constraint as 
	SELECT REF_ID, CONSTRAINT_ID, ALLOW_UPDATE, IS_RESPONSIBLE FROM tmp_dfa_constraint where CONN_ID = CONNECTION_ID();
	
create or replace view session_dfa_constraint as 
	SELECT CONSTRAINT_ID, ALLOW_UPDATE, IS_RESPONSIBLE FROM tmp_dfa_constraint where CONN_ID = CONNECTION_ID() AND REF_ID = 0;
	
